# Generated by Django 5.1.6 on 2025-03-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_user_profilepic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profilepic",
            field=models.ImageField(
                blank=True,
                default="media/profilepics/default.png",
                null=True,
                upload_to="media/profilepics/",
            ),
        ),
    ]
