# Generated by Django 5.1.6 on 2025-03-11 09:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_user_profilepic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genrename", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("zipcode", models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="profilename",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artistimage",
                    models.ImageField(
                        blank=True,
                        default="media/artistpics/default.png",
                        null=True,
                        upload_to="media/artistpics/",
                    ),
                ),
                (
                    "artistfans",
                    models.ManyToManyField(
                        related_name="artist_fans", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(related_name="artists", to="app.genre"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventArtists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_artist",
                        to="app.artist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eventname", models.CharField(max_length=100)),
                ("eventdate", models.DateField()),
                ("eventtime", models.TimeField()),
                ("eventdescription", models.TextField()),
                (
                    "eventimage",
                    models.ImageField(
                        blank=True,
                        default="media/eventpics/default.png",
                        null=True,
                        upload_to="media/eventpics/",
                    ),
                ),
                ("ticketsold", models.IntegerField(default=0)),
                ("ticketprice", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "EventArtists",
                    models.ManyToManyField(
                        related_name="event_artists",
                        through="app.EventArtists",
                        to="app.artist",
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(related_name="events", to="app.genre"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="app.location",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="eventartists",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_artist",
                to="app.events",
            ),
        ),
        migrations.CreateModel(
            name="Fan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favartists",
                    models.ManyToManyField(
                        related_name="fan_favartists", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fan_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("genres", models.ManyToManyField(related_name="fans", to="app.genre")),
            ],
        ),
        migrations.CreateModel(
            name="Tickets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticketnumber", models.IntegerField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="app.events",
                    ),
                ),
                (
                    "fan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="app.fan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fan",
            name="eventsattended",
            field=models.ManyToManyField(
                related_name="fan_eventsattended",
                through="app.Tickets",
                to="app.events",
            ),
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("venuecapacity", models.IntegerField()),
                (
                    "venueimage",
                    models.ImageField(
                        blank=True,
                        default="media/venuepics/default.png",
                        null=True,
                        upload_to="media/venuepics/",
                    ),
                ),
                (
                    "venuephotoreel",
                    models.ImageField(
                        blank=True,
                        default="media/venuepics/default.png",
                        null=True,
                        upload_to="media/venuepics/",
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(related_name="venues", to="app.genre"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venue_location",
                        to="app.location",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venue_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venuefans",
                    models.ManyToManyField(
                        related_name="venue_fans", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="events",
            name="eventvenue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_venue",
                to="app.venue",
            ),
        ),
    ]
