# Generated by Django 5.1.6 on 2025-03-11 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_genre_location_user_bio_user_profilename_artist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickets",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="artist",
            name="artistfans",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="artist_fans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="artist",
            name="genres",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="artists", to="app.genre"
            ),
        ),
        migrations.AlterField(
            model_name="fan",
            name="genres",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="fans", to="app.genre"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("fan", "Fan"),
                    ("artist", "Artist"),
                    ("venue", "Venue"),
                    ("doorman", "Doorman"),
                ],
                default="fan",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="genres",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="venues", to="app.genre"
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="venuefans",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="venue_fans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Doorman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doorman_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="events",
            name="authorized_doormen",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="events", to="app.doorman"
            ),
        ),
    ]
