# Generated by Django 5.1.6 on 2025-03-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_tickets_is_used_alter_artist_artistfans_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profilepic",
            field=models.ImageField(
                blank=True,
                default="profilepics/default.png",
                null=True,
                upload_to="profilepics/",
            ),
        ),
    ]
