# Generated by Django 5.1.6 on 2025-03-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_user_profilepic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="artistimage",
            field=models.ImageField(
                blank=True,
                default="artistpics/default.png",
                null=True,
                upload_to="artistpics/",
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="eventimage",
            field=models.ImageField(
                blank=True,
                default="eventpics/default.png",
                null=True,
                upload_to="eventpics/",
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="venueimage",
            field=models.ImageField(
                blank=True,
                default="venuepics/default.png",
                null=True,
                upload_to="venuepics/",
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="venuephotoreel",
            field=models.ImageField(
                blank=True,
                default="venuepics/default.png",
                null=True,
                upload_to="venuepics/",
            ),
        ),
    ]
