# Generated by Django 5.1.6 on 2025-05-06 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_artist_artistimage_alter_events_eventimage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("artist", "Artist"), ("venue", "Venue")],
                        max_length=10,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("date", models.DateField()),
                ("description", models.TextField()),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_artist",
                        to="app.artist",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_venue",
                        to="app.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("artist__isnull", False), ("venue__isnull", True)
                            ),
                            models.Q(
                                ("artist__isnull", True), ("venue__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="artist_or_venue_only",
                    )
                ],
            },
        ),
    ]
