# Generated by Django 5.1.6 on 2025-05-08 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_availability"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="availability",
            options={"ordering": ["start_time"]},
        ),
        migrations.RemoveField(
            model_name="availability",
            name="date",
        ),
    ]
