# Generated by Django 5.1.6 on 2025-05-10 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_remove_venue_venuephotoreel_photoreel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photoreel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
