# Generated by Django 5.1.6 on 2025-05-10 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_photoreel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photoreel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photoreel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
