# Generated by Django 5.1.6 on 2025-05-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_availability_options_remove_availability_date"),
        ("app", "0011_alter_photoreel_user"),
    ]

    operations = []
